version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Suitome_app
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: Suitome_db
    environment:
      MYSQL_DATABASE: Suitome
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: Suitome
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Suitome_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  mysql_data:
