version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Suitome:/var/www/html
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: suitome-app
    volumes:
      - ./Suitome:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=Suitome
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Suitome
